### PR TITLE
Set params test

### PR DESCRIPTION
**Pull request by ahmad11111111111**

### CODE REVIEW

**Comment by ahmad11111111111** [comment]
i readded the pull request

**Comment by kevincar** [comment]
Did you mean to start a new one? Or should we continue working with #9 ?

**Comment by ahmad11111111111** [comment]
Got it

**Comment by ahmad11111111111** [comment]
i figured out how to force a push, but theres just one error thats weird

**Comment by ahmad11111111111** [comment]
``` pythonLocation: /opt/hostedtoolcache/Python/3.8.17/x[6](https://github.com/umnil/preprocessing-pipeline/actions/runs/5742821049/job/15565751049?pr=10#step:5:6)4
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.8.17/x64/lib
./pipeline/psdbinner.py:46:12: E[7](https://github.com/umnil/preprocessing-pipeline/actions/runs/5742821049/job/15565751049?pr=10#step:5:8)21 do not compare types, for exact checks use `is` / `is not`, for instance checks use `isinstance()` ```

**Comment by ahmad11111111111** [comment]
the psdbinner file doesnt have 46 lines of code

**Comment by kevincar** [comment]
When are you getting this error?

**Comment by ahmad11111111111** [comment]
on the flake8

**Comment by kevincar** [comment]
There is a line 46 [here](https://github.com/ahmad11111111111/preprocessing-pipeline/blob/5f2202c70b0c1359f66dee41f8fdd07b812a8634/pipeline/psdbinner.py#L46)

We may need to adjust the conditional check to use `isinstance` instead of `==`

**Comment by ahmad11111111111** [comment]
ok

**Comment by ahmad11111111111** [comment]
ok

**Comment by ahmad11111111111** [comment]
got it!

**Comment by kevincar** [comment]
Good work! Merging now

**Pull request merged**
